
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_AXI_IIC_MAIN_DEVICE_ID,
		XPAR_AXI_IIC_MAIN_BASEADDR,
		XPAR_AXI_IIC_MAIN_TEN_BIT_ADR,
		XPAR_AXI_IIC_MAIN_GPO_WIDTH
	}
};


